---
name: Java CI

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.4]

    steps:
      - uses: actions/checkout@v2

      - name: Lint markdown file
        uses: nosborn/github-action-markdown-cli@v2.0.0
        with:
          files: .
      - name: Lint yaml files
        uses: ibiqlik/action-yamllint@v3

      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Codecov
        uses: codecov/codecov-action@v1.3.1
